import argparse
import json
import os
from datetime import datetime as dt
from pathlib import Path

import julian
import numpy as np
import pyTMD
from scipy.interpolate import interp1d


def create_tide_bc_static(
    path_results,
    path_tides,
    tide_model,
    tide_num,
    cbdry_used,
    grid_dims,
):


    """ "
    Input: grid[0] the size of first dimension of MITgcm domain
    grid[1] the size of second dimension of MITgcm domain
    cbdry_used, cell array specify which boundary to add tidal
    boundary condition,
    {'s', 'n', 'w', 'e'}, South, North, West, and East
    If there is no ocean points on one boundary, do not specify it.
    Otherwise it will generate an error in interpolation.
    tide_num: tidal components to be included in tidal BC file
    Output: Static part of tidal boundary conditions will be saved in npy files to be later use by set_bc_tides_corrections.py
    Note:
    1) The script will read boundary grid file bdry_grid_[swne].npy
        generated by set_bc_grid_MER_ST.py

    2) The following ten  tidal constituents can be included
              m2  s2  n2  k2  k1  o1  p1  q1 mf mm
              1   2   3   4   5   6   7   8  9  10
    """

    # Dimension of Boundary files
    NX = grid_dims[0]
    NY = grid_dims[1]

    # Set the Boundary to add tides
    # AngleCS_bc, AngleSN_bc are the Cos and Sin and angle
    # of U axis of MITgcm
    # from due east

    for c_bdry in cbdry_used:

        bdry_file = path_results / f"bdry_grid_{c_bdry}.npy"
        print(bdry_file)
        data = np.load(bdry_file, allow_pickle=True).item()
        for name, arr in data.items():
            print("loaded_array:\n", name, arr.shape)
            print(name, arr.shape,"min/max:", np.nanmin(arr), np.nanmax(arr))
        lat_bc = data["lat_bc"]
        lon_bc = data["lon_bc"]
        depth_bc = data["depth_bc"]
        AngleCS_bc = data["AngleCS_bc"]
        AngleSN_bc = data["AngleSN_bc"]

        boundary = c_bdry.upper()

        OBlength = NX if boundary in ["N", "S"] else NY
        print("\n --------------------------------------------------\n")
        print(
            "Computing the static part of the tidal forcing on boundary",
            c_bdry,
            "\n over a grid of lon size",
            len(lon_bc),
            "and lat size",
            len(lat_bc),
        )
        ## Load tide model

        # TMDwidgets = pyTMD.tools.widgets()
        # TMDwidgets.directory.value = path_tides
        # print("directory", TMDwidgets.directory.value)
        # model = pyTMD.io.model(
        #     TMDwidgets.directory.value, compressed=TMDwidgets.compress.value
        # ).current(tide_model)

        model = pyTMD.io.model(path_tides).current(tide_model)

        ## Extract tidal constants for each constituent (harmonic constants)

        # Returned phases are Greenwich phases or Greenwich phase lag (in degrees)
        # pyTMD returns one value per boundary grid point for each constituent
        # in tide_num. However some points are NaN and these NaNs can appear
        # anywhere along the boundary. Because of this we later do intp_line_safe
        uamp, upha, conlist0 = model.extract_constants(
            lon_bc,
            lat_bc,
            type="U",
            constituents=tide_num,
            method="bilinear",
            extrapolate="linear",
        )
        vamp, vpha, conlist0 = model.extract_constants(
            lon_bc,
            lat_bc,
            type="V",
            constituents=tide_num,
            method="bilinear",
            extrapolate="linear",
        )

        print("Tidal constants extracted in ", c_bdry, " boundary")

        if uamp.shape[0] != len(tide_num):
            uamp = np.transpose(uamp)
            vamp = np.transpose(vamp)
            upha = np.transpose(upha)
            vpha = np.transpose(vpha)


        ## Loop over constituents

        # create out arrays for all boundary points and all constituents data
        L = NX if boundary in ['N','S'] else NY

        u_amp_st = np.zeros((L, len(conlist0)))
        u_pha_st_deg = np.zeros((L, len(conlist0)))

        v_amp_st = np.zeros((L, len(conlist0)))
        v_pha_st_deg = np.zeros((L, len(conlist0)))


        print("Filling NaNs along the boundary for each constituent or substituting by 0 if depth_bc is 0 (land)")
        for i, c in enumerate(conlist0):

            coord_1d = np.arange(len(uamp[i,:]))

            ua_c = intp_line_safe(uamp[i,:], coord_1d, depth_bc) # Fill NaNs along a 1-D boundary line
            up_c = intp_line_safe(upha[i,:], coord_1d, depth_bc)
            va_c = intp_line_safe(vamp[i,:], coord_1d, depth_bc)
            vp_c = intp_line_safe(vpha[i,:], coord_1d, depth_bc)

            u_amp_st[:,i] = ua_c
            u_pha_st_deg[:,i] = up_c
            v_amp_st[:,i] = va_c
            v_pha_st_deg[:,i] = vp_c

        print("Saving static results for each constitutent")

        fname_lon = "data_lon_" + c_bdry + ".npy"
        fname_lat = "data_lat_" + c_bdry + ".npy"
        fname_depth = "data_depth_" + c_bdry + ".npy"
        fname_u_am_st_all = "data_u_am_st_all_" + c_bdry + ".npy"
        fname_u_ph_st_all_deg = "data_u_ph_st_all_deg_" + c_bdry + ".npy"
        fname_v_am_st_all = "data_v_am_st_all_" + c_bdry + ".npy"
        fname_v_ph_st_all_deg = "data_v_ph_st_all_deg_" + c_bdry + ".npy"

        np.save(path_results / fname_lon, lon_bc)
        np.save(path_results / fname_lat, lat_bc)
        np.save(path_results / fname_depth, depth_bc)
        np.save(path_results / fname_u_am_st_all, u_amp_st)
        np.save(path_results / fname_u_ph_st_all_deg, u_pha_st_deg)
        np.save(path_results / fname_v_am_st_all, v_amp_st)
        np.save(path_results / fname_v_ph_st_all_deg, v_pha_st_deg)

    return True


def intp_line_safe(values, coord, depth_bc):
    """
    Fill NaNs along a 1-D boundary line, with special handling for zero depth.

    If depth_bc is 0, the corresponding value is forced to 0 without interpolation.
    Interpolation is performed only for points where depth_bc != 0 and value is NaN.

    Input:
        values:  array, may contain NaN
        coord:   index/coordinates of values (1D, same length as values)
        depth_bc: depths corresponding to values (same shape as values)
    Output:
        values_int: array without NaN (zeros where depth_bc == 0)
    """

    # Make a copy to avoid modifying the original input
    values_int = values.copy()

    # Force all points where depth_bc is exactly 0 to be 0
    zero_depth_mask = (depth_bc == 0)
    values_int[zero_depth_mask] = 0

    # Define masks ONLY for points with non-zero depth
    non_zero_depth_mask = ~zero_depth_mask

    # Among non-zero depth points, find which are good (finite) and bad (NaN/Inf)
    goodp = np.isfinite(values) & non_zero_depth_mask
    badp = ~np.isfinite(values) & non_zero_depth_mask

    # If we don't have at least 2 good points, we cannot interpolate safely.
    # Fill remaining NaNs (at non-zero depths) with 0 to keep output NaN-free.
    if np.sum(goodp) < 2:
        values_int[badp] = 0
        return values_int

    # Build interpolation function using ONLY the good points with non-zero depth
    f = interp1d(
        coord[goodp], values[goodp],
        kind="linear",
        fill_value="extrapolate"
    )

    # Fill the bad points (that have non-zero depth) using the interpolation
    values_int[badp] = f(coord[badp])

    return values_int


def main(path_results, path_tides, tide_model, constituents, boundaries, grid_dims):
    print("\n-----------------------------------------------------")
    print(f"Results path:          {path_results}")
    print(f"Tidal hc data path:    {path_tides}")
    print(f"Tidal model of hc data:{tide_model}")
    print(f"Constituents:          {constituents}")
    print(f"Boundaries:            {boundaries}")
    print(f"Grid dimensions:       {grid_dims}")
    print("\n-----------------------------------------------------")
    print("\nCreating MITgcm static part of Tidal BC")

    grid_dims = list(map(int, grid_dims))

    path_results = Path(path_results).expanduser().resolve()
    path_tides = Path(path_tides).expanduser().resolve()

    print("Domain sides", boundaries, "with constituents", constituents)
    create_tide_bc_static(
        path_results,
        path_tides,
        tide_model,
        constituents,
        boundaries,
        grid_dims,
    )


if __name__ == "__main__":
    # load default values from JSON (if exists)
    default_config = {}
    json_path = "tides_config_new.json"
    if Path(json_path).exists():
        with open(json_path) as f:
            default_config = json.load(f)
    # if present set up argparse that overrides JSON
    parser = argparse.ArgumentParser(
        description="Script for creating the static part of tidal boundary condition\
        for MITgcm (*.obcs)\ninputs can be provided by json dictionary\
        and/or by command line,ls\nthese overide json inputs."
    )
    subparsers = parser.add_subparsers(title="subcommand", dest="subcommand")
    parser.add_argument(
        "--path_results",
        default=default_config.get("path_results"),
        help=(
            "path to the folder where static results are saved and where the results of\
            set_bc_grid have been saved"
        ),
    )
    parser.add_argument(
        "--path_tide_hc_data",
        default=default_config.get("path_tide_hc_data"),
        help=("path to the folder containing tide hc data"),
    )
    parser.add_argument(
        "--tide_model",
        default=default_config.get("tide_model"),
        help=("name of the tide model"),
    )

    parser.add_argument(
        "--constituents",
        nargs="+",  # accetta una lista di valori separati da spazio
        default=default_config.get("constituents"),
        help=("Constituent list"),
    )
    parser.add_argument(
        "--boundaries",
        nargs="+",  # accetta una lista di valori separati da spazio
        default=default_config.get("boundaries"),
        help=("Boundary list where tides have to be added"),
    )
    parser.add_argument(
        "--grid_dims",
        nargs="+",  # accetta una lista di valori separati da spazio
        default=default_config.get("grid_dims"),
        help="number of grid points in each dimension (longitude, latitude, depth): nx, ny, nz",
    )

    args = parser.parse_args()

    main(
        args.path_results,
        args.path_tide_hc_data,
        args.tide_model,
        args.constituents,
        args.boundaries,
        args.grid_dims,
    )
